### ISSUE TITLE
运行起来之后没有自动按方向键&空格

### ISSUE THREAD

**Issue by amosnothing** [chen365409389/CrazyDancer#1]
我用的visual studio 运行的sln和csproj文件

**Comment by JackQChen** [comment]
目前这个代码还需要Arduino Micro才能模拟点击，如果是PS2的键盘的话，可以用WinIo模拟按键

**Comment by amosnothing** [comment]
啊 ？ 不怎么熟悉C，一脸懵逼。

**Comment by amosnothing** [comment]
还有几个问题：
1. 玩11键的时候，有些按钮是捕获不到的，显示不完整
2. 游戏的窗口是不是一定要固定在屏幕的左上角，而且还不能改变修改窗口大小？

**Comment by JackQChen** [comment]
1.这个需要再加点模板
2.窗口的话这个我周末改改，不用固定位置和大小

**Comment by amosnothing** [comment]
谢谢您了，自动模拟空格点击的问题，我也自个研究一下。

**Comment by JackQChen** [comment]
今天试了下好久没上客户端要重新下载，十几个G还是算了，你可以参考这个项目的处理方式<br>
[链接地址](https://github.com/CSA/CrazyRestaurant/blob/master/CrazyRestaurant/Common/AppInvoke.cs)<br>
大致过程如下：<br>
1.用Spy++找到窗体标题和类信息<br>
2.用FindWindow和FindWindowEx获取句柄，然后用MoveWindow固定窗体位置和大小<br>
3.使用DC相关操作，通过句柄获取到当前窗体截图（里面的GetImage方法）<br>
4.图像识别和处理相关<br>
5.模拟键盘或鼠标操作，第一种方式可以用SendMessage向窗体发送消息，这种方式好处就是目标窗体可以最小化，系统中没有实际的按键或者鼠标操作，不影响其他应用，不过有些DirectInput的游戏可能模拟不了。还有一种方式，如果是PS2键盘，可以用WinIo库模拟。最后一种没有PS2键盘，可以用Arduino Micro插到电脑上来模拟，最后两种方式都比较底层，一般都能模拟成功，不过会影响其他应用）
